repositories:
  - name: jetstack
    url: https://charts.jetstack.io

releases:
  - name: cert-manager
    chart: jetstack/cert-manager
    version: v1.10.0
    namespace: cert-manager
    values:
      - values/cert-manager.yaml
    installed: true
  - name: mychart
    chart: .
    namespace: mychart
    values:
      - values/mychart.yaml
    needs:
      - cert-manager/cert-manager
    installed: true
